name: Discord Notifications

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send message to Discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          payload=$(jq -n \
            --arg repo "$GITHUB_REPOSITORY" \
            --arg author "$GITHUB_ACTOR" \
            --arg msg "${{ github.event.head_commit.message }}" \
            '{content: ("Push to " + $repo + "\n" + $author + ": " + $msg)}')
          curl -H "Content-Type: application/json" \
               -d "$payload" \
               "$DISCORD_WEBHOOK"
